import LoadHTMLContainer from '/js/components/LoadHTMLContainer.js';
const app = new LoadHTMLContainer();
app.addHTML('#Header', '/html/components/Header.html');
app.addHTML('#Footer', '/html/components/Footer.html');
app.addHTML('#Hero-content', '/html/contents/Index/herocontent.html');
app.addHTML('#loginContainer', '/html/contents/Index/login-form.html');
app.addHTML('#authContainer', '/html/contents/Index/auth-container.html');
app.addJS('/js/components/SessionManager.js');
app.addJS('/js/components/login.js');
app.run();
